const pickupLines = {
    operators: [
        "Are you Thermite? Because you just breached my heart.",
        "Are you Caveira? Because you've been silently stealing my heart.",
        "Are you Dokkaebi? Because you're ringing all the right bells.",
        "Are you Jäger? Because I want you to protect my heart.",
        "Are you Sledge? Because you just smashed through my defenses.",
        "Are you Ash? Because you're fast and explosive.",
        "Are you Bandit? Because you're shocking my system.",
        "Are you Pulse? Because I can feel my heart rate rising around you.",
        "Are you Valkyrie? Because I want you to keep an eye on me.",
        "Are you Echo? Because you've left me stunned.",
        "Are you Denari? Because you're worth your weight in gold.",
        "Are you Rauora? Because you've got me feeling healed.",
        "Are you Skopós? Because you've got me in your sights.",
        "Are you Striker? Because you hit me right in the feels.",
        "Are you Sentry? Because I want you watching over me.",
        "Are you Deimos? Because you're hauntingly beautiful.",
        "Are you Tubarão? Because you've got me frozen in place.",
        "Are you Ram? Because you're breaking down all my barriers.",
        "Are you Fenrir? Because I'm trapped in your gaze.",
        "Are you Brava? Because you've hacked into my heart.",
        "Are you Solis? Because you see right through me.",
        "Are you Grim? Because you've got me swarmed with emotions.",
        "Are you Sens? Because you're blinding me with beauty.",
        "Are you Azami? Because you've created the perfect barrier around my heart.",
        "Are you Thorn? Because I'm drawn to your dangerous beauty.",
        "Are you Osa? Because you're transparently perfect.",
        "Are you Thunderbird? Because you've revived my spirits.",
        "Are you Flores? Because you're driving me crazy.",
        "Are you Aruni? Because you've opened the gates to my heart.",
        "Are you Zero? Because you've pierced through my defenses.",
        "Are you Ace? Because you're making my heart flow.",
        "Are you Melusi? Because you've slowed me down in the best way.",
        "Are you Oryx? Because you've knocked me off my feet.",
        "Are you Iana? Because I can't tell if you're real or a dream.",
        "Are you Wamai? Because you're pulling me toward you.",
        "Are you Kali? Because you've got a one-shot chance with me.",
        "Are you Amaru? Because you've swooped into my heart.",
        "Are you Goyo? Because you've set my heart on fire.",
        "Are you NØKK? Because you've disappeared with my heart.",
        "Are you Warden? Because I see clearly when I'm with you.",
        "Are you Mozzie? Because you've taken over my thoughts.",
        "Are you Gridlock? Because I'm stuck on you.",
        "Are you Nomad? Because you've knocked me over.",
        "Are you Kaid? Because you've electrified my soul.",
        "Are you Clash? Because you've got me shocked and slowed.",
        "Are you Maverick? Because you're quietly breaking down my walls.",
        "Are you Maestro? Because I can't stop watching you.",
        "Are you Alibi? Because I can't tell what's real anymore.",
        "Are you Lion? Because you've got me scanning for your attention.",
        "Are you Finka? Because you give me a boost.",
        "Are you Vigil? Because you make my heart beat erratically.",
        "Are you Zofia? Because you withstand anything I throw at you.",
        "Are you Ela? Because you've got me concussed with love.",
        "Are you Ying? Because you're blindingly beautiful.",
        "Are you Lesion? Because you've got me stuck on you.",
        "Are you Mira? Because I see my future with you.",
        "Are you Jackal? Because you're tracking straight to my heart.",
        "Are you Hibana? Because you're opening new possibilities.",
        "Are you Capitão? Because you're smoking hot.",
        "Are you Blackbeard? Because you're shielding my heart.",
        "Are you Buck? Because you're opening up new levels of love.",
        "Are you Frost? Because I've fallen for you.",
        "Are you Mute? Because you've silenced all my doubts.",
        "Are you Smoke? Because you're toxic in the best way.",
        "Are you Thatcher? Because you've EMP'd my heart.",
        "Are you Castle? Because you're barricading my heart from others.",
        "Are you Montagne? Because you've got me fully extended.",
        "Are you Twitch? Because you've shocked me into love.",
        "Are you Doc? Because you've stimmed my heart.",
        "Are you Rook? Because I want you to protect me.",
        "Are you Blitz? Because you've flashed me with your smile.",
        "Are you IQ? Because you detect all my feelings.",
        "Are you Fuze? Because my heart's exploding for you.",
        "Are you Glaz? Because I see you clearly in my future.",
        "Are you Tachanka? Because you're my lord and savior.",
        "Are you Kapkan? Because you've trapped my heart."
    ],
    maps: [
        "Are you Club House? Because I want to spend all night exploring you.",
        "Are you Oregon? Because you're my favorite destination.",
        "Are you Coastline? Because you're hot and I want to dive in.",
        "Are you Border? Because I can't get past how amazing you are.",
        "Are you Bank? Because I want to make a deposit in your heart.",
        "Are you Villa? Because you're classy and full of surprises.",
        "Are you Theme Park? Because you're a thrilling ride.",
        "Are you Kafe Dostoyevsky? Because you're making me weak in the knees.",
        "Are you Outback? Because you're wild and untamed.",
        "Are you Consulate? Because you're diplomatic and gorgeous.",
        "Are you Chalet? because you make my fireplace burn"
    ],
    gadgets: [
        "Are you a breach charge? Because you just blew me away.",
        "Are you a deployable shield? Because I want you to protect my heart.",
        "Are you barbed wire? Because I'm caught up in you.",
        "Are you a nitro cell? Because you're explosive and dangerous.",
        "Are you a drone? Because I can't take my eyes off you.",
        "Are you a claymore? Because you're one step away from making my heart explode.",
        "Are you a bulletproof camera? Because I can't stop watching you.",
        "Are you a proximity alarm? Because you've got me on high alert.",
        "Are you a hard breach charge? Because you're breaking down my walls.",
        "Are you a stim pistol? Because you've got me feeling revived.",
        "Are you a MAG-NET? Because you're attracting all my attention.",
        "Are you a Denarii Bank? Because I want to invest in you.",
        "Are you a Health Kit? Because you make me feel better.",
        "Are you a Targeting Sensor? Because you detect all my feelings.",
        "Are you a Breaching Hammer? Because you're breaking through to me.",
        "Are you a Security Camera? Because I can't look away.",
        "Are you a Tracker Dart? Because you're following my heart.",
        "Are you a Cryo Canister? Because you've frozen me in place.",
        "Are you a Breaching Buster? Because you're breaking all my barriers.",
        "Are you a Fear Mine? Because I'm trapped by you.",
        "Are you a Kludge Drone? Because you've hacked my heart.",
        "Are you a SPEC-IO Scanner? Because you see right through me.",
        "Are you a Kawan Hive? Because my feelings are swarming.",
        "Are you a R.O.U. Projector? Because you're dazzling me.",
        "Are you a Kiba Barrier? Because you've secured my heart.",
        "Are you a Razorbloom? Because I'm drawn to your danger.",
        "Are you a Talon Shield? Because you're transparently perfect.",
        "Are you a Kona Station? Because you revive my spirits.",
        "Are you a RCE-Ratero? Because you're driving me to you.",
        "Are you a Surya Gate? Because you've opened up to me.",
        "Are you an Argus Camera? Because you see everything about me.",
        "Are you a SELMA Breacher? Because you're opening my heart.",
        "Are you a Banshee? Because you've slowed my world down.",
        "Are you a Remah Dash? Because you've knocked me over.",
        "Are you a Gemini Replicator? Because I see double of your beauty.",
        "Are you a CSRX 300? Because you've shot straight to my heart.",
        "Are you a Garra Hook? Because you've grabbed me.",
        "Are you a Volcan Shield? Because you're burning me up.",
        "Are you a HEL Presence Reduction? Because you've disappeared with my thoughts.",
        "Are you a Glance Smartglasses? Because I see clearly with you.",
        "Are you a Pest? Because you've captured my attention.",
        "Are you Trax Stingers? Because I'm stuck on you.",
        "Are you an Airjab? Because you've sent me flying.",
        "Are you an Rtila Electroclaw? Because you've electrified me.",
        "Are you a CCE Shield? Because you've got me shocked.",
        "Are you a Breaching Torch? Because you're melting my heart.",
        "Are you an Evil Eye? Because I'm watching you constantly.",
        "Are you a Prisma? Because I'm seeing multiple versions of you.",
        "Are you an EE-ONE-D? Because you've scanned my soul.",
        "Are you an Adrenal Surge? Because you give me a boost.",
        "Are you an ERC-7? Because you make my heart disappear.",
        "Are you a KS79 Lifeline? Because you withstand my storms.",
        "Are you a Grzmot Mine? Because you've concussed me.",
        "Are you a Candela? Because you're blindingly beautiful.",
        "Are you a Gu Mine? Because I'm stuck on you.",
        "Are you a Black Mirror? Because I see my reflection in you.",
        "Are you an Eyenox? Because you're tracking my heart.",
        "Are you an X-KAIROS? Because you're opening me up.",
        "Are you a Tactical Crossbow? Because you've hit the mark.",
        "Are you a Rifle Shield? Because you're protecting my feelings.",
        "Are you a Skeleton Key? Because you're unlocking my heart.",
        "Are you a Welcome Mat? Because I've fallen for you.",
        "Are you a Signal Disruptor? Because you've silenced my doubts.",
        "Are you a Remote Gas Grenade? Because you're intoxicating.",
        "Are you an EMP Grenade? Because you've disabled my defenses.",
        "Are you an Armor Panel? Because you're barricading my heart.",
        "Are you an Extendable Shield? Because you've got me fully extended.",
        "Are you a Shock Drone? Because you've shocked me into love.",
        "Are you a Stim Pistol? Because you've revived my love.",
        "Are you an Armor Pack? Because I want your protection.",
        "Are you a Flash Shield? Because you've flashed me.",
        "Are you an Electronics Detector? Because you detect all my secrets.",
        "Are you a Cluster Charge? Because my heart's exploding.",
        "Are you a Flip Sight? Because I see you clearly.",
        "Are you a Shumikha Grenade Launcher? Because you're burning me up.",
        "Are you an EDD? Because you've trapped my heart."
    ]
};

const categorySelect = document.getElementById('category');
const rizzButton = document.getElementById('rizz-button');
const pickupLineElement = document.getElementById('pickup-line');

rizzButton.addEventListener('click', function() {
    const selectedCategory = categorySelect.value;
    const lines = pickupLines[selectedCategory];
    const randomLine = lines[Math.floor(Math.random() * lines.length)];
    
    pickupLineElement.textContent = randomLine;
});
